name: agarwal_school
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  custom_sliding_segmented_control: ^1.8.4
  dynamic_color: ^1.7.0
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  html: ^0.15.0
  http: ^1.2.2
  provider:
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  animated_icon: ^0.0.9
  staggered_grid_view_flutter: ^0.0.4
  text_scroll: ^0.2.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  checkmark: ^0.0.2+1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: broken
      fonts:
        - asset: assets/fonts/broken.ttf
    - family: broken_filled
      fonts:
        - asset: assets/fonts/broken_filled.ttf
    - family: LexendDeca
      fonts:
        # - asset: assets/fonts/LexendDeca/LexendDeca-Black.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Bold.ttf
        # - asset: assets/fonts/LexendDeca/LexendDeca-ExtraBold.ttf
        # - asset: assets/fonts/LexendDeca/LexendDeca-ExtraLight.ttf
        
    - family: LexendDeca-thin
      fonts:
        # - asset: assets/fonts/LexendDeca/LexendDeca-Medium.ttf
        # - asset: assets/fonts/LexendDeca/LexendDeca-Regular.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Light.ttf
        # - asset: assets/fonts/LexendDeca/LexendDeca-SemiBold.ttf
        # - asset: assets/fonts/LexendDeca/LexendDeca-Thin.ttf
